-- GENERATED by the bake step (scripts/bake.ts) - do not edit by hand.
-- Vendor prices and recipes this addon has learned, handed back to the game as code, because this client
-- never reads saved data back. Logic.applyBaked fills the gaps with it at load; learned-this-session wins.
-- The copy in git is empty on purpose: what was learned on the beta stays out of git history (rule C16).
-- The installed copy is written from data/baked/ by the install scripts.

local _, ns = ...

ns.baked = {
    builtAt = 0,
    vendor = {
    },
    recipes = {
    },
}
